name: Daily Commit

on:
  schedule:
    - cron: '0 0,12 * * *'   # Runs at 00:00 UTC and 12:00 UTC (2 times a day)
  workflow_dispatch:         # Allow manual run from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Make a Commit
        run: |
          echo "Automated commit on $(date)" >> log.txt
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add log.txt
          git commit -m "chore: daily commit $(date)" || echo "No changes"
          git push
