name: Daily Commit with Random Snippets

on:
  schedule:
    # Twice a day at 9:00 and 21:00 UTC
    - cron: "0 9,21 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch Random Snippet & Commit
        run: |
          mkdir -p snippets
          FILE="snippets/snippet_$(date +%Y-%m-%d_%H-%M-%S).txt"

          # Try ZenQuotes API
          RESPONSE=$(curl -s https://zenquotes.io/api/random || echo "")

          if echo "$RESPONSE" | jq -e . >/dev/null 2>&1; then
            QUOTE=$(echo "$RESPONSE" | jq -r '.[0].q + " — " + .[0].a')
          else
            # Try Programming Quotes API as backup
            RESPONSE=$(curl -s https://programming-quotesapi.vercel.app/api/random || echo "")

            if echo "$RESPONSE" | jq -e . >/dev/null 2>&1; then
              QUOTE=$(echo "$RESPONSE" | jq -r '.en + " — " + .author')
            else
              # Final fallback: random snippets
              SNIPPETS=(
                "console.log('Hello from GitHub Actions!');"
                "print('Hello from GitHub Actions!')"
                "#include <iostream>\nint main(){ std::cout << \"Hello from GitHub Actions!\"; return 0; }"
                "echo 'Hello from GitHub Actions!'"
                "System.out.println('Hello from GitHub Actions!');"
              )
              INDEX=$((RANDOM % ${#SNIPPETS[@]}))
              QUOTE="${SNIPPETS[$INDEX]}"
            fi
          fi

          echo -e "$QUOTE" > $FILE

          # ✅ Use your own GitHub identity
          git config user.name "Ayush Kumar"
          git config user.email "ayushkumar12030@gmail.com"

          git add snippets
          git commit -m "chore: add random snippet on $(date)" || echo "No changes"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
