name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'   # Runs once per day at 00:00 UTC
  workflow_dispatch:       # Allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Make a Commit
        run: |
          echo "Automated commit on $(date)" >> log.txt
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add log.txt
          git commit -m "chore: daily commit $(date)" || echo "No changes"
          git push

