- name: Fetch Random Snippet & Commit
  run: |
    mkdir -p snippets
    FILE="snippets/snippet_$(date +%Y-%m-%d_%H-%M-%S).txt"

    # Try fetching a random quote (replace API with a stable one)
    QUOTE=$(curl -s https://zenquotes.io/api/random | jq -r '.[0].q + " — " + .[0].a')

    # Fallback if API fails
    if [ -z "$QUOTE" ]; then
      QUOTE="console.log('Hello from GitHub Actions!');"
    fi

    echo "$QUOTE" > $FILE

    git config --global user.name "GitHub Action"
    git config --global user.email "actions@github.com"
    git add snippets
    git commit -m "chore: add random snippet on $(date)" || echo "No changes"
    git push
